/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EasyAdmin;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.RandomAccessFile;
import javax.swing.JOptionPane;
import EasyAdmin.Employee;
import EasyAdmin.Managers;

/**
 *
 * @author 3406446
 */
public class AddStaff extends javax.swing.JFrame {

    String fname = " ";
    String lname = " ";
    int Age = 0;
    double salary = 0.0;
    String phoneNum = " ";
    String Address = " ";
    String department = " ";
    int employeeNumber = 0;
    int yearsOfService = 0;
    String gender = " ";
    boolean manager = false;
    RandomAccessFile raf;  // define first file instance
    RandomAccessFile raf2; // second
    String FileName = ("EmployeesFile.txt");
    File inFile = new File(FileName);
    String File2 = ("ManagersFile.txt");
    File sndFile = new File(File2);
    boolean restart;
    public AddStaff() {
        initComponents();
        restart=false;
        //Checking file state  DO NOT MODIFY!!!!!!!!!!!!!!!!!!!!!!!!!!
        if (inFile.exists() && inFile.length() != 0) {
            try {
                raf = new RandomAccessFile(inFile, "rw"); // open file
                System.out.println("File opened");
            } catch (IOException ex) {
                ex.printStackTrace();
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Employee profile could not be found, creating a blank file");
            String ten = "          ";
            String fields[] = new String[250];
            for (int i = 0; i < fields.length; i++) {
                fields[i] = ten + ten + ten + ten + ten + ten + ten + ten + ten + ten + ten + " ";//111 spaces
            }
            writefile(fields, FileName);
            restart=true;
        }
        // Employees File opened
        //checking ManagerFile
            if (sndFile.exists() && sndFile.length() != 0) {
                try {
                    raf2 = new RandomAccessFile(sndFile, "rw"); // open file
                    System.out.println("File opened");
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Manager profile could not be found, creating a blank file");
                String ten = "          ";
                String fields[] = new String[10];
                for (int i = 0; i < fields.length; i++) {
                    fields[i] = ten + ten + ten + ten + ten;//50 spaces
                }
                writefile(fields, File2);
                restart=true;
            }
        // Managers File opened
        // restart to prevent null-pointer reached
        if(restart){
            JOptionPane.showMessageDialog(null, "File instances have been created and initialized. "
                    + "Please restart the program");
            System.exit(0);
            restart=false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        first = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pNum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        eNum = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        last = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        posn = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("NewStaff");

        jLabel1.setText("New Employee");

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        first.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstFocusLost(evt);
            }
        });

        age.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ageFocusLost(evt);
            }
        });

        jLabel3.setText("Age");

        jLabel4.setText("Phone Number");

        jLabel5.setText("Home Address");

        jLabel6.setText("Employee Number");

        eNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                eNumFocusLost(evt);
            }
        });

        jLabel7.setText("Department");

        jLabel8.setText("(first)");

        last.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastFocusLost(evt);
            }
        });

        jLabel9.setText("(last)");

        jLabel10.setText("Salary");

        sal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                salFocusLost(evt);
            }
        });

        jLabel11.setText("Gender");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));

        posn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administration", "Inventory", "Sales", "Storage", "Delivering", "Finance", "Quality Control" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee", "Manager" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eNum))
                            .addComponent(pNum, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(first, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(last, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(191, 191, 191)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(posn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 16, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(first, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(eNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(posn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(sal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:        
        Employee temp = new Employee();
        Managers input = new Managers();
        // Get data entered
        fname = first.getText();
        lname = last.getText();
        Age = Integer.parseInt(age.getText());
        salary = Double.parseDouble(sal.getText());
        phoneNum = pNum.getText();
        Address = address.getText();
        department = posn.getSelectedItem().toString();
        employeeNumber = Integer.parseInt(eNum.getText());
        gender = jComboBox2.getSelectedItem().toString();
        temp.loadinfo(fname + lname, Age, gender, salary, phoneNum, Address, department, employeeNumber, manager);       
        if (jComboBox3.getSelectedItem().toString().equalsIgnoreCase("Manager")) {
            manager = true;
            temp.ifManager(manager);
            input.loadinfo(fname + lname, Age, gender, salary, phoneNum, Address, department, employeeNumber, manager);
            getEntered(input);
            input.changeCode(Integer.parseInt(JOptionPane.showInputDialog("Please set a code for authorizing absences!")));
            int index=posn.getSelectedIndex();
            if(checkUnique(index,raf2,51)){
                writeInfo(temp, raf);
                writeInfo(input, raf2);
            }
            else{
                JOptionPane.showMessageDialog(null, "Not able to create manager under"
                        + " selected department \nBecause department manager exist!", "Conflict", 1);
            }
        }
        else{
             writeInfo(temp, raf);
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void firstFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstFocusLost
        // TODO add your handling code here:
        String in = first.getText();
        String alphas = "qwertyuiopasdfghjklzxcvbnm QWERTYUIOPLKJHGFDSAZXCVBNM";
        for (int i = 0; i < in.length(); i++) {
            if (alphas.indexOf(in.charAt(i)) < 0) {
                JOptionPane.showMessageDialog(null, "Field not enterred correctly", "Warning", 1);
                first.setText("");
                break;
            }
        }
    }//GEN-LAST:event_firstFocusLost

    private void lastFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastFocusLost
        // TODO add your handling code here:
        String in = last.getText();
        String alphas = "qwertyuiopasdfghjklzxcvbnm QWERTYUIOPLKJHGFDSAZXCVBNM";
        for (int i = 0; i < in.length(); i++) {
            if (alphas.indexOf(in.charAt(i)) < 0) {
                JOptionPane.showMessageDialog(null, "Field not enterred correctly", "Warning", 1);
                last.setText("");
                break;
            }
        }
    }//GEN-LAST:event_lastFocusLost

    private void ageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFocusLost
        // TODO add your handling code here:
        String in = (age.getText());
        String ints = "1234567890";
        for (int i = 0; i < in.length(); i++) {
            if (ints.indexOf(in.charAt(i)) < 0) {
                JOptionPane.showMessageDialog(null, "Field not enterred correctly", "Warning", 1);
                age.setText("");
                break;   
            }
        }
    }//GEN-LAST:event_ageFocusLost

    private void eNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_eNumFocusLost
        // TODO add your handling code here:
        String in = (eNum.getText());
        String ints = "1234567890";
        for (int i = 0; i < in.length(); i++) {
            if (ints.indexOf(in.charAt(i)) < 0) {
                JOptionPane.showMessageDialog(null, "Field not enterred correctly", "Warning", 1);
                break;
            }
            if(Integer.parseInt(eNum.getText())>0&&Integer.parseInt(eNum.getText())<=200){
            if(checkUnique(Integer.parseInt(eNum.getText())-1,raf,112)){
                System.out.println("Unique primary Key!");
            }
            else{
                JOptionPane.showMessageDialog(null, "Employee Number Has been Taken!", "Warning", 1);
                eNum.setText("");
            }
            }
            else{
                JOptionPane.showMessageDialog(null, "Please enter a number from 1 to 200", "Warning", 1);
                eNum.setText("");
            }
        }
        
    }//GEN-LAST:event_eNumFocusLost

    private void salFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salFocusLost
        // TODO add your handling code here:
        String in = (sal.getText());
        String ints = "1234567890.";
        for (int i = 0; i < in.length(); i++) {
            if (ints.indexOf(in.charAt(i)) < 0) {
                JOptionPane.showMessageDialog(null, "Field not enterred correctly", "Warning", 1);
                sal.setText("");
                break;
            }
        }
    }//GEN-LAST:event_salFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStaff().setVisible(true);
            }
        });
    }

    public void getEntered(Managers temp) {
        System.out.println("Information entered; Name: " + temp.getName() + " ,aged " + temp.getAge() + " " + gender
                + ", in " + temp.getPosn() + " department." + " Employee Number: " + temp.getENUM()
                + " With a salary of $" + temp.getSal() + " monthly" + "\nPhone Number: " + temp.getPhone() + ".");
    }
    public boolean checkUnique(int temp, RandomAccessFile raf,final int length){
         boolean unique = false;
         String in="";
         
        try{
            raf.seek(temp*length);
            in=raf.readLine();
        }
        catch(IOException ex) {
            ex.printStackTrace();
        }  
       String anything = "1234567890qwertyuiopasdfghjklzxcvbnmQWERTYUIOPLKJHGFDSAZXCVBNM";// no space
        for (int i = 0; i < in.length(); i++) {
            if (anything.indexOf(in.charAt(i)) >= 0) {
                System.out.println(i);
            unique=false;
            break;
        } 
            else{
                unique=true;
                break;
            }
        }
        
        return unique;
                
    }
    public static void writefile(String variables[], String fName) {
        try {
            PrintWriter out = new PrintWriter(new FileWriter(fName));
            for (int i = 0; i < variables.length; i++) {
                out.println(variables[i]);  // output the values to the "out" stream
            }
            out.close();  // output to file
        } catch (java.io.IOException e) {
            System.out.println(e);
        }
    }

    public void writeInfo(Employee temp, RandomAccessFile raf) {
        final int length = 112; // 111 characters plus EOFL
        int count = temp.getENUM() - 1;
        try {
            raf.seek(count * length);
            raf.writeBytes(temp.getName());
            raf.seek(count * length + 20);
            raf.writeBytes(Integer.toString(temp.getAge()));
            raf.seek(count * length + 25);
            raf.writeBytes(Double.toString(temp.getSal()));
            raf.seek(count * length + 35);
            raf.writeBytes(temp.getPhone());
            raf.seek(count * length + 47);
            raf.writeBytes(Integer.toString(temp.GetDays()));
            raf.seek(count * length + 50);
            raf.writeBytes(temp.getAddress());
            raf.seek(count * length + 70);
            raf.writeBytes(temp.getPosn());
            raf.seek(count * length + 85);
            raf.writeBytes(Integer.toString(temp.getENUM()));
            raf.seek(count * length + 90);
            raf.writeBytes(temp.getGender());
            raf.seek(count * length + 100);
            raf.writeBytes(temp.getIfManager());
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    public void writeInfo(Managers temp, RandomAccessFile raf) {
        final int length = 51; // 50 characters plus EOFL  
        int count = posn.getSelectedIndex();
        try {
            raf.seek(count * length);
            raf.writeBytes(fname + lname);
            raf.seek(count * length + 20);
            raf.writeBytes(department);
            raf.seek(count * length + 35);
            raf.writeBytes(Integer.toString(temp.getCode()));
            
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JTextField eNum;
    private javax.swing.JTextField first;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField last;
    private javax.swing.JTextField pNum;
    private javax.swing.JComboBox<String> posn;
    private javax.swing.JTextField sal;
    // End of variables declaration//GEN-END:variables
}
